### ISSUE TITLE
Unable to add Homebridge to HomeKit after installing/configuring the smartthings plugin

### ISSUE THREAD

**Issue by jojogrosso** [tonesto7/homebridge-smartthings-v2#34] opened 2019-12-31 22:03 UTC
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [X] The SmartApp and Device Handler are using the latest code available.
-  [X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 1 light switch
-  Mobile App Version(Not required):
-  SmartApp Version: 2.0.1
-  Device Handler Version:
-  Homebridge Version: 0.4.50
-  NodeJS Version: 12.14.0

## Expected Behavior
**Tell us what you think should be happening**
I have a switch, that's added to the SmartThings App. The switch is a Meross switch, from the Meross app (not sure if that would have anything to do with this). Once I add the SmartThings plugin to Homebridge, I would think the devices should then appear in HomeKit.
## Current Behavior
**What happens instead of the expected behavior?**
Once I add the SmartThings plugin to Homebridge, all of my devices using HomeBridge (just a Nest Thermostat for now) shows "No Response." In Homebridge, the light switch shows up in the Accessories tab. I'm also unable to add Homebridge as a bridge to HomeKit if I have the SmartThings plugin installed/configured. Once I remove the smartthings plugin and remove it from the config file, the Nest device shows responsive again.

In Homebridge, the Services shows as running and the console is listening.
## Steps to Reproduce (for bugs)
The steps is really just installed the smartthings v2 plugin and configuring it.

## Context
**How has this issue affected you? What are you trying to accomplish?
I'm not sure if I'm doing something wrong, or missing a step. Hope this is the correct place to post this. Thanks.

---
Please include a copy of any relevant log output to assist in tracking down the bug

**Comment by tonesto7** [comment] 2020-01-02 20:39
Search how to view homebridge logs and it will point you to the cause of the error.
Did you upgrade from v1 of my plugin?

**Comment by jojogrosso** [comment] 2020-01-03 02:10
Thanks for replying. I didn't upgrade, I never used your old plugin. I just started using Homebridge recently.

> [INFO]: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded!
[1/2/2020, 8:50:22 PM] [DEBUG]: Refreshing All Device Data
[1/2/2020, 8:50:22 PM] [ERROR]: getDevices Error:  403 - {"error":true,"type":"AccessDenied","message":"This request is not authorized by the specified access token"}
[1/2/2020, 8:50:22 PM]

Could that be why? I confirmed the access token is correct in the app.

**Comment by jojogrosso** [comment] 2020-01-04 13:51
I got rid of that error, but only by using the newer SmartThings app. When using the classic app, the appID and token doesn't seem to be saving, as well as the device I add to the Homebridge v2 SmartApp within the SmartThings app.

But I'm still having the issue where all of my homebridge devices aren't responding in the HomeKit app in iOS. I can't seem to find any errors in the smartthings log of the homebridge log. 

Any other ideas on what might be happening?

**Comment by tonesto7** [comment] 2020-01-05 15:15
It seems you are not alone and I suspect this is related to a recent ST platform update.
I will reach out to my contacts at ST and see if this is a know issue.

**Comment by tonesto7** [comment] 2020-01-07 21:53
Should be resolved in the new v2.1.0 I just pushed out.

**Closed as completed by tonesto7** 2020-01-07 21:53 UTC
Labels: bug
