### ISSUE TITLE
[ISSUE] Thermostat `this.platform.getTempUnit()` Error

### ISSUE THREAD

**Issue by hardlock75** [tonesto7/homebridge-smartthings-v2#17] opened 2019-12-17 02:19 UTC
First,
I would like to thank you for your project and for being active there. I even took the time to give you a donation even if I am not rich.
------------
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 1 device thermostat not working
-  Mobile App Version(Not required):
-  SmartApp Version: homebrige V 2.0.2
-  Device Handler Version: 
-  Homebridge Version: hub V2
-  NodeJS Version: V13.3.0

## Expected Behavior and ## Current Behavior
**Tell us what you think should be happening**
-When i start in terminal hombridge i have red error " This.platform.getTempUnit is not a fonction"

-In Homekit first, i don't see the anbiant temperature of the room. but the real problem is, when i put thermostat Temperature in 25 because is winter. He doesn't  start to heat. In the log on my Raspberry PI 4 when Hombridge is running no activity on real time log.

- When change temperature on my SmartThings (classic) on the same thermostat, is heating and i see activity on raspberry PI 4 real time log.  image 3

 - I forget something, i try procedur when is lock and unlock the heating not working  the Lock i working when i dont wanna  child change temperature on direct thermostat and is working. 

-----------
I have the impression that the Homekit doesn't speak to the homebridge of the raspberry Pi

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug
![2019-12-16 20_43_26-error1](https://user-images.githubusercontent.com/58529389/70958093-23e17880-2046-11ea-8d19-74f9ed4bf871.png)

![2019-12-16 21_09_14-iphone](https://user-images.githubusercontent.com/58529389/70958848-77ed5c80-2048-11ea-8486-49c1b01100b4.png)

![2019-12-16 21_16_20-bug 3](https://user-images.githubusercontent.com/58529389/70959453-54c3ac80-204a-11ea-8a5f-36e505c73a75.png)

**Comment by hardlock75** [comment] 2019-12-17 02:22
i forget image 3 sorry

![2019-12-16 21_16_20-bug 3](https://user-images.githubusercontent.com/58529389/70959373-19c17900-204a-11ea-9240-b5f0197bf2d7.png)

**Comment by tonesto7** [comment] 2019-12-17 15:12
Thanks for the details I will attempt to troubleshoot this

**Comment by tonesto7** [comment] 2019-12-17 17:26
I've corrected the issue and it will be deployed in the next 30 minutes

**Comment by hardlock75** [comment] 2019-12-17 23:36
Thank you for your responsiveness, I updated Smartapps 2.0.3 and plugin 2.0.10. Error message in red is gone but I have another problem. I imagine that I have to open another repport problem? or i continu in this report?

**Comment by tonesto7** [comment] 2019-12-18 03:51
depends on what the issue is

**Comment by hardlock75** [comment] 2019-12-18 05:38
impossible for me to cool the room or heat the room. Because when Thermostat is added on smartapp. I go in the homekit, the thermostat starting to heat maximum 40 celcius. Is impossible do change temp. see my pic for more explication. for clear, the problem doesn't come from the lock. Since I tested with or without.

I have no choice, to withdraw in smartapps because the room would be too hot. 

I restart the raspberry pi, and homebridge many time, and i have samething.

![thermostat](https://user-images.githubusercontent.com/58529389/71058700-afcecf80-212e-11ea-9f66-4f5dc8968a53.png)

**Comment by hardlock75** [comment] 2019-12-18 05:53
is it possible to integrate temperature sensor in thermostat info, like samething on m'y closing sensor door?
sorry for my big picture
![closing sensor](https://user-images.githubusercontent.com/58529389/71059413-d4c44200-2130-11ea-9035-65f474cd8d86.png)

**Comment by tonesto7** [comment] 2019-12-18 14:43
If the thermostat exposes the attributes for those items they would show.  I recommend filtering out the lock capability using the SmartApp filter section. 

To help further debug there is now a new version of the app with a new Input called Device Data Viewer.
Select your thermostat under one of the 3 inputs and share the data that's shown there

**Comment by hardlock75** [comment] 2019-12-18 16:18
Yes the thermostat expose ambient attribute
![62025482-0FB0-4816-A00D-476D08C2A097](https://user-images.githubusercontent.com/58529389/71103440-2350fb00-2188-11ea-916f-0235d6d3de10.jpeg)

**Comment by hardlock75** [comment] 2019-12-18 16:19
There is input device log

{
    "name": "Sinop\u00e9 RDC Bureau Carlos TH1124ZB",
    "basename": "Sinope TH1124ZB Thermostat",
    "deviceid": "9b8dc1f5-accb-4da7-948d-07b5af9f4fe4",
    "status": "ONLINE",
    "manufacturer": "Sinope Technologies",
    "model": "TH1124ZB",
    "deviceNetworkId": "091F",
    "lastActivity": "2019-12-18T16:06:09+0000",
    "capabilities": [
        "Temperature Measurement",
        "Configuration",
        "Lock",
        "Refresh",
        "Actuator",
        "Thermostat Mode",
        "Thermostat Operating State",
        "Thermostat Heating Setpoint",
        "Thermostat Setpoint",
        "Health Check"
    ],
    "commands": [
        "configure",
        "lock",
        "unlock",
        "refresh",
        "off",
        "heat",
        "emergencyHeat",
        "cool",
        "auto",
        "setThermostatMode",
        "setHeatingSetpoint",
        "ping",
        "heatLevelUp",
        "heatLevelDown"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "temperature": 18.7,
        "lock": "locked",
        "thermostatMode": "heat",
        "supportedThermostatModes": "[off, heat]",
        "thermostatOperatingState": "idle",
        "heatingSetpoint": 17.0,
        "thermostatSetpoint": null,
        "checkInterval": 1800,
        "DeviceWatch-DeviceStatus": null,
        "healthStatus": null,
        "DeviceWatch-Enroll": null,
        "temperatureDisplayMode": null,
        "heatingSetpointRangeHigh": 30.0,
        "heatingSetpointRangeLow": 5.0,
        "heatingSetpointRange": {
            "x": 5.0,
            "y": 30.0,
            "z": null
        },
        "outdoorTemp": null,
        "verboseTrace": null
    },
    "eventHistory": [
        "Wed Dec 18 15:59:44 UTC 2019 | [temperature] | (18.7 C)",
        "Wed Dec 18 15:44:41 UTC 2019 | [temperature] | (18.8 C)",
        "Wed Dec 18 15:34:39 UTC 2019 | [temperature] | (18.9 C)",
        "Wed Dec 18 15:24:37 UTC 2019 | [temperature] | (19.0 C)",
        "Wed Dec 18 15:09:33 UTC 2019 | [temperature] | (19.1 C)",
        "Wed Dec 18 14:54:30 UTC 2019 | [temperature] | (19.2 C)",
        "Wed Dec 18 14:44:28 UTC 2019 | [temperature] | (19.3 C)",
        "Wed Dec 18 14:39:27 UTC 2019 | [temperature] | (19.4 C)",
        "Wed Dec 18 14:24:24 UTC 2019 | [temperature] | (19.5 C)",
        "Wed Dec 18 14:19:23 UTC 2019 | [temperature] | (19.6 C)",
        "Wed Dec 18 14:09:21 UTC 2019 | [temperature] | (19.7 C)",
        "Wed Dec 18 14:04:20 UTC 2019 | [temperature] | (19.8 C)",
        "Wed Dec 18 13:59:19 UTC 2019 | [temperature] | (19.9 C)",
        "Wed Dec 18 13:54:18 UTC 2019 | [temperature] | (20.1 C)",
        "Wed Dec 18 13:49:17 UTC 2019 | [temperature] | (20.3 C)",
        "Wed Dec 18 13:44:16 UTC 2019 | [temperature] | (20.5 C)",
        "Wed Dec 18 13:39:15 UTC 2019 | [temperature] | (20.8 C)",
        "Wed Dec 18 13:35:11 UTC 2019 | [thermostatOperatingState] | (idle)",
        "Wed Dec 18 13:35:11 UTC 2019 | [heatingDemand] | (0)",
        "Wed Dec 18 13:35:08 UTC 2019 | [heatingSetpoint] | (17.0 C)"
    ]
}

**Comment by tonesto7** [comment] 2020-01-07 21:49
Should be resolved in the new v2.1.0 I just pushed out.

**Closed as completed by tonesto7** 2020-01-07 21:49 UTC
Labels: bug

**Comment by hardlock75** [comment] 2020-01-08 12:41
Not working after updating smartapp v2.1.0  and Homebridge plugin v2..1
——
{
    "name": "Sinop\u00e9 RDC Bureau Carlos TH1124ZB",
    "basename": "Sinope TH1124ZB Thermostat",
    "deviceid": "9b8dc1f5-accb-4da7-948d-07b5af9f4fe4",
    "status": "ONLINE",
    "manufacturer": "Sinope Technologies",
    "model": "TH1124ZB",
    "deviceNetworkId": "091F",
    "lastActivity": "2020-01-08T12:36:36+0000",
    "capabilities": [
        "Actuator",
        "Configuration",
        "Health Check",
        "Lock",
        "Refresh",
        "Temperature Measurement",
        "Thermostat Heating Setpoint",
        "Thermostat Mode",
        "Thermostat Operating State",
        "Thermostat Setpoint"
    ],
    "commands": [
        "auto",
        "configure",
        "cool",
        "emergencyHeat",
        "heat",
        "heatLevelDown",
        "heatLevelUp",
        "lock",
        "off",
        "ping",
        "refresh",
        "setHeatingSetpoint",
        "setThermostatMode",
        "unlock"
    ],
    "customflags": [
        
    ],
    "attributes": {
        "DeviceWatch-DeviceStatus": null,
        "DeviceWatch-Enroll": null,
        "checkInterval": 1800,
        "healthStatus": null,
        "heatingSetpoint": 21.0,
        "heatingSetpointRange": {
            "x": 5.0,
            "y": 30.0,
            "z": null
        },
        "heatingSetpointRangeHigh": 30.0,
        "heatingSetpointRangeLow": 5.0,
        "lock": "locked",
        "outdoorTemp": null,
        "supportedThermostatModes": "[off, heat]",
        "temperature": 21.4,
        "temperatureDisplayMode": null,
        "thermostatMode": "heat",
        "thermostatOperatingState": "idle",
        "thermostatSetpoint": null,
        "verboseTrace": null
    },
    "eventHistory": [
        "Wed Jan 08 12:35:54 UTC 2020 | [temperature] | (21.4 C)",
        "Wed Jan 08 12:31:36 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Wed Jan 08 12:31:36 UTC 2020 | [heatingDemand] | (0)",
        "Wed Jan 08 12:30:52 UTC 2020 | [temperature] | (21.1 C)",
        "Wed Jan 08 12:26:51 UTC 2020 | [thermostatOperatingState] | (heating)",
        "Wed Jan 08 12:26:51 UTC 2020 | [heatingDemand] | (12)",
        "Wed Jan 08 12:25:50 UTC 2020 | [temperature] | (21.2 C)",
        "Wed Jan 08 12:20:49 UTC 2020 | [temperature] | (21.5 C)",
        "Wed Jan 08 12:20:06 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Wed Jan 08 12:20:06 UTC 2020 | [heatingDemand] | (0)",
        "Wed Jan 08 12:18:06 UTC 2020 | [thermostatOperatingState] | (heating)",
        "Wed Jan 08 12:18:06 UTC 2020 | [heatingDemand] | (14)",
        "Wed Jan 08 12:17:06 UTC 2020 | [thermostatOperatingState] | (idle)",
        "Wed Jan 08 12:17:06 UTC 2020 | [heatingDemand] | (0)",
        "Wed Jan 08 12:16:21 UTC 2020 | [heatingDemand] | (10)",
        "Wed Jan 08 12:15:44 UTC 2020 | [temperature] | (21.2 C)",
        "Wed Jan 08 12:14:06 UTC 2020 | [heatingDemand] | (22)",
        "Wed Jan 08 12:10:43 UTC 2020 | [temperature] | (20.9 C)",
        "Wed Jan 08 12:10:21 UTC 2020 | [heatingDemand] | (32)",
        "Wed Jan 08 12:09:21 UTC 2020 | [heatingDemand] | (22)"
    ]
}
![image](https://user-images.githubusercontent.com/58529389/71986788-09409080-31fb-11ea-9032-458024c15ffd.png)

![image](https://user-images.githubusercontent.com/58529389/71980610-739f0400-31ee-11ea-800e-9a7031849167.png)

![image](https://user-images.githubusercontent.com/58529389/71980759-d55f6e00-31ee-11ea-9847-f8d1eba2c6e5.png)

**Comment by hardlock75** [comment] 2020-01-10 04:54
hi tonesto7
there is big news... almost works. the problem is when i Heating set point to 22 celsius exemple. The thermostat start to heat, but when i exit homekit and i re-open homekit on my iphone. Is stay to 20 celsius but the heating set point is 22.

![image](https://user-images.githubusercontent.com/58529389/72126725-33996780-333b-11ea-8a13-93d68fb1bd3c.png)
![image](https://user-images.githubusercontent.com/58529389/72126775-67748d00-333b-11ea-99b5-c26446032caa.png)

When i re-open Homekit there is the information

![image](https://user-images.githubusercontent.com/58529389/72126851-b4f0fa00-333b-11ea-9f72-ea1fe4ad9e28.png)

the information was not saved in the log.

Is it possible to interrogate the heating set point thermostat and push the information in the home kit? i don't know if is possible...
