### ISSUE TITLE
Homebridge-smartthings-v2 will not save devices

### ISSUE THREAD

**Issue by cdillinger27** [tonesto7/homebridge-smartthings-v2#129] opened 2020-04-18 15:52 UTC
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x ] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
-  Mobile App Version(Not required):
-  SmartApp Version:2.3.2
-  Device Handler Version:
-  Homebridge Version:  4.15.1
-  NodeJS Version:  12.16.2

## Expected Behavior
Once installed, selecting a device should save once backed out of the smart app.

## Current Behavior
Devices not saving.  I installed v2 for the first time using ST community installer - have not had any other versions previous to this one installed.  Would not save devices.  Removed and re-installed manually following all steps with the same result.

I am not a programmer, but following the steps was pretty straight-forward and went without issue.  However, still having the same result.

**Comment by bhmeade** [comment] 2020-04-25 06:24
I'm having the same problem.

**Comment by tonesto7** [comment] 2020-04-26 12:34
Are you using the new SmartThings app or classic?

**Comment by cdillinger27** [comment] 2020-04-27 12:29
Using the classic app.  Since posting, apple home is showing and functioning with the devices, however ST still not saving devices.  Functionally, it is working, but just not showing the devices added in ST.

**Comment by tonesto7** [comment] 2020-04-27 18:18
what do you mean it's not saving the devices?  
Out of curiosity are you using Android?
If yes,  After selecting devices and pressing done.  let it sit for a couple of seconds before moving to another page

**Comment by cdillinger27** [comment] 2020-04-28 00:30
Not using android - using ios, classic app, homebridge V2.  When I go into homebridge app and click on either "define device type" or "select your devices" and configure/set the devices and then save all the way out, and then go back in, all of the selections are gone - shows "0 Selected".  This is still occurring, however, is now showing up in apple home and functioning, but still shows "0 Selected".

**Comment by ahamill85** [comment] 2020-04-28 02:47
I'm also having the same issue. I also noticed my app ID and token change every time I open "Render the platform data for homebridge config.json".

iOS 13.3.1
homebridge v1.0.2
homebridge-smartthings-v2 v2.3.2

**Comment by bhmeade** [comment] 2020-04-28 04:24
> I'm also having the same issue. I also noticed my app ID and token change every time I open "Render the platform data for homebridge config.json".
> 
> iOS 13.3.1
> homebridge v1.0.2
> homebridge-smartthings-v2 v2.3.2

Yes, I saw the same thing. I keep updating those values in my config.json file only to find that they have changed again the next time I look.

**Comment by tonesto7** [comment] 2020-04-28 13:34
I wonder if the plugin is having issues with the new homebridge 1.x
I will do some testing

**Comment by ahamill85** [comment] 2020-04-28 14:08
Thanks for looking in to it. Quick note, I noticed I get several instances of the HomeBridge v2 smart app appearing in my list of installed smart apps under my location in the IDE. Don't know what that means, just thought I'd share.

**Comment by tonesto7** [comment] 2020-04-28 18:51
You will need to remove the excess instances of the smart apps.

I've been playing with the smart app some and can't duplicate the issue with saving devices.

**Comment by ahamill85** [comment] 2020-04-28 19:16
I removed all of the excess instances, but I believe they are recreated every time I try to save options for the smart app. I'm going to reinstall this afternoon and post my settings and some other errors I've seen that might shed some light.

**Comment by cdillinger27** [comment] 2020-04-28 22:51
Okay tonesto7 - thanks for taking a look at it.

**Comment by ahamill85** [comment] 2020-04-29 01:34
**Update**
Everything I configure when I first open the app is able to be used by synced to homebridge, but any subsequent opening of the homebridge-smartthings app, causes a new app/configuration to be created. Essentially, I can't figure out how to edit a previous setup in the homebridge-smartthings settings. Not sure if that helps hint at where the issue is.

**Comment by tonesto7** [comment] 2020-04-29 13:12
Can you do a screen recording on the process you are taking to access the smart app after you've completed the setup the first time?

**Comment by tonesto7** [comment] 2020-04-29 13:13
Once you've installed an app you access it under automation tab at bottom and then the smartapps tab at the top.

**Comment by ahamill85** [comment] 2020-04-29 13:50
That was it. I was reopening the initial app setup and never looked under automation. I apologize for this mixup. I'm pretty new to SmartThings, so maybe that part of was common sense. I followed this tutorial as well as the installation instructions within this GitHub repo and I don't think there's a mention of the automations tab, which might be helpful.  Thanks for your help with this and for the work you've done on this project.

**Comment by tonesto7** [comment] 2020-04-30 04:37
No worries...  There was a point when I was in your shoes and learning the ropes here :)

**Closed as completed by tonesto7** 2020-04-30 04:37 UTC
Labels: bug
